{% set name = "lab" %}
{% set version = "0.22.0" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zaquestion/lab/archive/v{{ version }}.tar.gz
  sha256: ff5b184db71818d0c342788fd5b38ab7c7af8d8561c683b5d08ffd4075116a0d

build:
  number: 0
  script:
    - go install -ldflags "-X main.version={{ version }}" .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    # Lab needs a tty even for `lab --help`
    - which lab  # [unix]
    - where lab  # [win]

about:
  home: https://github.com/zaquestion/lab
  license: CC0-1.0
  license_file: LICENSE
  summary: Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab

  doc_url: https://zaquestion.github.io/lab
  dev_url: https://github.com/zaquestion/lab

extra:
  recipe-maintainers:
    - sodre
